# Generated by Django 4.2 on 2024-02-27 09:38

from django.db import migrations, models

import src.vacancies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='calary',
            field=models.CharField(blank=True, default='0', null=True, validators=[src.vacancies.validators.calary_validator]),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='format_work',
            field=models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hubrid'), ('office', 'office')], default='office'),
        ),
    ]
