# Generated by Django 4.2 on 2024-02-27 17:42

from django.db import migrations, models
import src.vacancies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_resume_activity_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='calary',
            field=models.CharField(blank=True, default='0', null=True, validators=[src.vacancies.validators.calary_validator]),
        ),
    ]
