# Generated by Django 4.2 on 2024-03-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_resume_calary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='respond',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
