# Generated by Django 4.2 on 2024-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_options_respond_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='answer',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
