# Generated by Django 4.2 on 2024-03-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0006_respond_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond', to='vacancies.respond')),
            ],
        ),
    ]
