# Generated by Django 4.2 on 2024-03-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0006_respond_answer'),
        ('notifications', '0002_message_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='respond_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respond', to='vacancies.respond'),
        ),
    ]
