# Generated by Django 4.2 on 2024-02-23 19:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import src.users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('staff', models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('101-1000', '101-1000'), ('1000+', '1000+')])),
                ('verify', models.BooleanField(default=False)),
                ('work_phone_number', models.CharField(blank=True, null=True, validators=[src.users.validators.validate_phone_number])),
                ('work_email', models.EmailField(max_length=254, unique=True)),
                ('site_address', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
